.pragma library

// Pedro GUI palette. Edit colors here to update every QML consumer.
// The reusable glass surface shares these values across the bar, dock, panels
// and desktop context menu. Blur softens the wallpaper; haze gives it a cloudy finish.
var menuBackground = "#2f2e2e"
var menuOpacity = 0.5
var menuBlur = 0.82
var menuHazeColor = "#7d7c7b"
var menuHazeOpacity = 0.11

// Base, text and type.
var accent = "#ffffff"
var clearBlack = "#00000000"
var desktopBackground = "#05080c"
var fontNormal = 15
var textMuted = "#d6dcdf"
var textPrimary = "#000000"
var vignetteBottom = "#26000000"
var vignetteTop = "#19000000"
var white = "#ffffff"

// Shared surfaces and interaction.
var actionHover = "#26ffffff"
var buttonBorder = "#40ffffff"
var cardBorder = "#36ffffff"
var cardBorderStrong = "#58ffffff"
var cardSurface = "#20ffffff"
var controlHover = "#12ffffff"
var controlPressed = "#1fffffff"
var dividerBright = "#55ffffff"
var dividerSoft = "#28ffffff"
var inputBackground = "#2b000000"
var menuBorder = "#526f6f6f"
var overlayHover = "#22ffffff"
var overlayPressed = "#34ffffff"
var overlaySelectedHover = "#18ffffff"
var overlaySubtle = "#16ffffff"
var shadowInner = "#2a000000"
var shadowOuter = "#18000000"
var shadowSoft = "#14000000"

// Windows and desktop selection.
var contextMenuTextMuted = "#aeb4b8"
var filesWindowBackground = "#2c2c2c"
var filesWindowBorder = "#454545"
var filesWindowText = "#dedede"
var filesWindowTitle = "#323232"
var selectionArea = "#5c315f99"
var selectionAreaBorder = "#d05f98d8"
var selectionText = "#15191e"
var shortcutHover = "#24ffffff"
var shortcutSelected = "#70315f99"
var shortcutSelectedBorder = "#c85f98d8"
var shortcutShadow = "#76352a24"
var windowClose = "#ff5f57"
var windowCloseGlyph = "#68110d"
var windowMaximize = "#28c840"
var windowMaximizeGlyph = "#0b5d18"
var windowMinimize = "#febc2e"
var windowMinimizeGlyph = "#765000"

// Navigation and system controls.
var batteryHealthy = "#24d687"
var controlOrbBackground = "#5d28264a"
var controlOrbBorder = "#609dbbff"
var controlOrbBottom = "#1445c8"
var controlOrbCenter = "#392ea0"
var controlOrbHighlight = "#c9f4ff"
var controlOrbHover = "#67413a5a"
var controlOrbMiddle = "#7948ff"
var controlOrbTop = "#6aeaff"
var navigationSelectedBorder = "#587daed8"
var navigationSelectedBottom = "#343d86"
var navigationSelectedTop = "#0000005d"
var notificationAccent = "#9ec8ff"
var profileBackground = "#555555"
var profileBorder = "#74ffffff"
var profileHover = "#80666666"
var sliderFill = "#5a9cff"
var sliderTrack = "#40506a"
var statusActive = "#579cff"
var statusConnected = "#41df91"
var statusInactive = "#8290a4"
var statusWifiConnected = "#75e3ad"
var switchActive = "#2582ff"
var switchActiveBorder = "#4a9aff"
var switchInactive = "#465366"
var switchInactiveBorder = "#607086"
var wifiConnectedSurface = "#1dffffff"
var wifiGlowInner = "#085a9cff"
var wifiGlowOuter = "#0d5a9cff"
var wifiNetworkBorder = "#45ffffff"
var wifiSignalStrong = "#9ac0ff"

// Media controls.
var mediaArtworkBackground = "#2a3748"
var mediaButtonBorder = "#42ffffff"

// Desktop illustrations.
var browserBottom = "#123dc0"
var browserLetter = "#e6ffffff"
var browserMiddle = "#167dd1"
var browserTop = "#12bfae"
var chatIconBackground = "#f8f8f5"
var chatIconBlue = "#53a4e6"
var chatIconGreen = "#38bc82"
var chatIconPink = "#e95372"
var chatIconYellow = "#f0bc40"
var codeIconBackground = "#252c35"
var codeIconBright = "#24a5f2"
var codeIconDark = "#07549b"
var controlSymbol = "#f4f7ff"
var designBlue = "#1abcfe"
var designCoral = "#ff7262"
var designGreen = "#0acf83"
var designOrange = "#f24e1e"
var designPurple = "#a259ff"
var dockDivider = "#75ffffff"
var dockIndicator = "#54b9ff"
var folderBottom = "#087be5"
var folderTab = "#59caff"
var folderTop = "#22baff"
var imageIconFrame = "#f6f4ef"
var musicIconBackground = "#16c864"
var musicIconStroke = "#173c31"
var notesBackground = "#f7f6f1"
var notesBorder = "#c9c8c4"
var notesLines = "#8b9398"
var photosBackground = "#fffdfb"
var photosBlue = "#4ea5dc"
var photosCenter = "#fff9ed"
var photosGreen = "#63ba57"
var photosOrange = "#f49b3f"
var photosPurple = "#a270c5"
var photosRed = "#ed484e"
var photosYellow = "#f5d84e"

// Ordered color model used to draw the Photos application mark.
var photosPalette = [photosRed, photosOrange, photosYellow, photosGreen, photosBlue, photosPurple]

var terminalIconBackground = "#202730"
var terminalIconText = "#f7f7f7"
var trashBorder = "#a6b0b5"
var trashBottom = "#9ca7ad"
var trashLid = "#e1e7e9"
var trashTop = "#f6f7f8"
var weatherCloud = "#f8f8f6"
var weatherPlace = "#f5f5f5"
var weatherSun = "#ffc42d"
