# Global Pedro preferences

[language]
current = "es"

[appearance]
mode = "dark" # "light" or "dark"

# Wallpaper configuration for dark themes
[wallpaper.dark]
type = "system"
current = "wallpaper.jpeg"

# Wallpaper configuration for light themes
[wallpaper.light]
type = "file"
current = "wallpaper.jpeg"

[dock]
hoverScale = 1.20 # 1.0 disables zoom; supported range: 1.0–1.3
