# Global Pedro preferences

[language]
current = "en"

[appearance]
mode = "dark" # "light" or "dark"

# Wallpaper configuration for dark themes
[wallpaper.dark]
type = "system"
current = "wallpaper.jpeg"

# Wallpaper configuration for light themes
[wallpaper.light]
type = "file"
current = "wallpaper.jpeg"
